name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4

      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      
      - name: Install dependencies
        run: npm install

      
      - name: Run tests
        run: npm test

      
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ci-cd-demo:latest .

      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ci-cd-demo:latest

      
      - name: Run container (deploy)
        run: |
          docker run -d -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/ci-cd-demo:latest
